### ISSUE TITLE
plugin RPC connection is not responding

### ISSUE THREAD

**Issue by basti-schr** [ONLYOFFICE/onlyoffice-mattermost#40]
Hi there,

I am trying to install the plugin but I have a similar issue as in #27, however we are not using S3 storage and have installed the latest version from the release page. The first time I try to open a file I get a 500 error, then a 404.
The OnlyOffice instance is successfully used with nextcloud.

From the console log after activating the plugin.
```
INF i18n/i18n.go:132 > timestamp=2023-07-20 23:05:18.288 Z msg=Loaded system translations for locale=de from locale=/mattermost/i18n/de.json

WRN api4/config.go:436 > timestamp=2023-07-20 23:05:24.934 Z msg=Unrecognized config permissions tag value. tag_value=sysconsole_write_*_read

ERR plugin/client_rpc.go:268 > timestamp=2023-07-20 23:05:25.192 Z msg=RPC call to OnActivate plugin failed. plugin_id=com.onlyoffice.mattermost error=unexpected EOF

ERR plugin/hclog_adapter.go:79 > timestamp=2023-07-20 23:05:25.192 Z msg=plugin process exited plugin_id=com.onlyoffice.mattermost wrapped_extras=pathplugins/com.onlyoffice.mattermost/server/dist/plugin-linux-amd64pid1338errorexit status 2

ERR plugin/client_rpc_generated.go:67 > timestamp=2023-07-20 23:05:25.195 Z msg=RPC call OnConfigurationChange to plugin failed. plugin_id=com.onlyoffice.mattermost error=connection is shut down

INF i18n/i18n.go:132 > timestamp=2023-07-20 23:05:25.201 Z msg=Loaded system translations for locale=de from locale=/mattermost/i18n/de.json

WRN plugin/health_check.go:59 > timestamp=2023-07-20 23:05:26.841 Z msg=Health check failed for plugin id=com.onlyoffice.mattermost error=plugin RPC connection is not responding

WRN plugin/hclog_adapter.go:70 > timestamp=2023-07-20 23:05:26.841 Z msg=error closing client during Kill plugin_id=com.onlyoffice.mattermost wrapped_extras=errconnection is shut down

WRN plugin/hclog_adapter.go:72 > timestamp=2023-07-20 23:05:26.841 Z msg=plugin failed to exit gracefully plugin_id=com.onlyoffice.mattermost

ERR plugin/client_rpc.go:268 > timestamp=2023-07-20 23:05:27.101 Z msg=RPC call to OnActivate plugin failed. plugin_id=com.onlyoffice.mattermost error=unexpected EOF

ERR plugin/hclog_adapter.go:79 > timestamp=2023-07-20 23:05:27.101 Z msg=plugin process exited plugin_id=com.onlyoffice.mattermost wrapped_extras=pathplugins/com.onlyoffice.mattermost/server/dist/plugin-linux-amd64pid1351errorexit status 2

WRN plugin/health_check.go:59 > timestamp=2023-07-20 23:05:56.841 Z msg=Health check failed for plugin id=com.onlyoffice.mattermost error=plugin RPC connection is not responding

WRN plugin/hclog_adapter.go:70 > timestamp=2023-07-20 23:05:56.841 Z msg=error closing client during Kill plugin_id=com.onlyoffice.mattermost wrapped_extras=errconnection is shut down

WRN plugin/hclog_adapter.go:72 > timestamp=2023-07-20 23:05:56.841 Z msg=plugin failed to exit gracefully plugin_id=com.onlyoffice.mattermost

ERR plugin/client_rpc.go:268 > timestamp=2023-07-20 23:05:57.099 Z msg=RPC call to OnActivate plugin failed. plugin_id=com.onlyoffice.mattermost error=unexpected EOF

ERR plugin/hclog_adapter.go:79 > timestamp=2023-07-20 23:05:57.099 Z msg=plugin process exited plugin_id=com.onlyoffice.mattermost wrapped_extras=pathplugins/com.onlyoffice.mattermost/server/dist/plugin-linux-amd64pid1371errorexit status 2
```

After opening a file:
```
WRN plugin/health_check.go:59 > timestamp=2023-07-20 23:06:26.841 Z msg=Health check failed for plugin id=com.onlyoffice.mattermost error=plugin RPC connection is not responding

WRN plugin/hclog_adapter.go:70 > timestamp=2023-07-20 23:06:26.841 Z msg=error closing client during Kill plugin_id=com.onlyoffice.mattermost wrapped_extras=errconnection is shut down

WRN plugin/hclog_adapter.go:72 > timestamp=2023-07-20 23:06:26.841 Z msg=plugin failed to exit gracefully plugin_id=com.onlyoffice.mattermost
```

Versions :

    Mattermost :  7.10.3 EE via docker
    Plugin : v1.1.1
    OnlyOffice Docs : 7.4.0 via docker

**Comment by Nsenz** [comment]
@basti-schr, hello there! Thanks for reporting the problem. We will look into it. @igwyd, could you please reproduce the bug?

**Comment by igwyd** [comment]
Hello @basti-schr i checked the installation of our plugin (v.1.1.1) on mattermost (7.10.3 EE in docker), also changed the localization to german, but didn't get any erros. Maybe your JWT header is default? "Authorization" header not allowed by mattermost, you must change it to custom (more details in the [readme](https://github.com/ONLYOFFICE/onlyoffice-mattermost#plugin-settings)). Are there any errors in the documentserver logs?

**Comment by basti-schr** [comment]
Thank you for your time. The JWT header is `AuthorizationJwt`.
The document server has no errors at all, it looks like the request is not being received there. 
Is there a problem with running the services behind a reverse proxy that terminates https? Or do I need to allow ports other than http/80?

**Comment by basti-schr** [comment]
To begin with we have a proxmox with a lxc container for the NGIX reverse Proxy and the OnlyOffice with reserved hardware resources. The Mattermost runs in a Virtual Machine with other services utilizing Portainer.

The Proxy settings are not special: the domain-name is forwarded to the cotainer ip and port with the Options `Chache Assets`, `Block Common Exploits` and `Websockets Support` activated as well as SSL from Lets Encrypt with all the Settings `Force SSL`, `HTTP/2 Support`, `HSTS Enabled` and `HSTS Support` enabeld.

Proxmox:
1. ReverseProxy (container 1)
	- NginxProxyManager
2. Nextcloud (container 2)
3. OnlyOffice (container 3)
	- onlyoffice stack
4. Portainer VM
	- Mattermost EE
		
		
**Mattermost docker stack**		
```yaml
version: "3"

services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data
  mattermost:
    depends_on:
      - postgres
    image: mattermost/mattermost-enterprise-edition:latest
    restart: unless-stopped
    volumes:
      - config:/mattermost/config
      - data:/mattermost/data
      - plugins:/mattermost/plugins
      - client-plugins:/mattermost/client/plugins
      - bleve:/mattermost/bleve-indexes
    environment:
      <redacted>
      # Plugin upload
      MM_PLUGINSETTINGS_ENABLEUPLOADS: true
    ports:
      - "82:8065"
      - "445:8443"
      - "8443:8443/udp"
volumes:
  postgres:
  config:
  data:
  plugins:
  client-plugins:
  bleve:
```

**OnlyOffice docker stack**
```yaml
version: '2'
services:
  onlyoffice-documentserver:
    image: onlyoffice/documentserver
    container_name: onlyoffice-documentserver
    depends_on:
      - onlyoffice-postgresql
      - onlyoffice-rabbitmq
    environment:
      - AMQP_URI=amqp://guest:guest@onlyoffice-rabbitmq
      - JWT_ENABLED=true
      - JWT_SECRET=<redacted>
      - JWT_HEADER=AuthorizationJwt
    ports:
      - '80:80'
    stdin_open: true
    restart: unless-stopped
    stop_grace_period: 60s
    volumes:
       - /var/www/onlyoffice/Data
       - /var/log/onlyoffice
       - /var/lib/onlyoffice/documentserver/App_Data/cache/files
       - /usr/share/fonts
       
  onlyoffice-rabbitmq:
    container_name: onlyoffice-rabbitmq
    image: rabbitmq
    restart: unless-stopped
    expose:
      - '5672'

  onlyoffice-postgresql:
    container_name: onlyoffice-postgresql
    image: postgres:9.5
    restart: unless-stopped
    expose:
      - '5432'
    volumes:
      - postgresql_data:/var/lib/postgresql

volumes:
  postgresql_data:

```
